# Tool: /Applications/ST/STEdgeAI/3.0/Utilities/mac/atonn
# Version atonn.1.1.3-8
# executed from dir /Applications/ST/STEdgeAI/3.0/Utilities/mac

load-mdesc-file="/Applications/ST/STEdgeAI/3.0/Utilities/configs/stm32n6"
load-cdesc-file="/Applications/ST/STEdgeAI/3.0/Utilities/configs/cortex-m55"
load-mpool-file="/Users/maksym.solovianchyk/Documents/Graduation_Internship/stm32ai-modelzoo-services/application_code/image_classification/STM32N6/Model/my_mpools/stm32n6-app2_STM32N6570-DK"
save-mpool-file="/Users/maksym.solovianchyk/Documents/Graduation_Internship/stm32ai-modelzoo-services/image_classification/tf/src/experiments_outputs/2026_02_23_15_41_24/neural_art__network/stm32n6-app2_STM32N6570-DK"
cache-maintenance=true
enable-virtual-mem-pools=true
native-float=true
json-quant-file="/Users/maksym.solovianchyk/Documents/Graduation_Internship/stm32ai-modelzoo-services/image_classification/tf/src/experiments_outputs/2026_02_23_15_41_24/mobilenetv2_a035_128_fft_int8_OE_3_3_1_Q.json"
optimization=3
Os=true
Omax-ca-pipe=4
Ocache-opt=true
enable-epoch-controller=true
output-info-file="c_info"
onnx-input="/Users/maksym.solovianchyk/Documents/Graduation_Internship/stm32ai-modelzoo-services/image_classification/tf/src/experiments_outputs/2026_02_23_15_41_24/mobilenetv2_a035_128_fft_int8_OE_3_3_1.onnx"
out-dir-prefix="/Users/maksym.solovianchyk/Documents/Graduation_Internship/stm32ai-modelzoo-services/image_classification/tf/src/experiments_outputs/2026_02_23_15_41_24/neural_art__network/"
c-output="network"
network-name="network"
all-buffers-info=true
generate-stai=true
Oauto-sched=true
