model:
   model_path: /Users/maksym.solovianchyk/Documents/Graduation_Internship/radar_ai_detector/stm32ai-modelzoo-services/image_classification/tf/src/experiments_outputs/2026_03_30_15_47_20/saved_models/best_model.keras 
operation_mode: quantization

dataset:
  dataset_name: custom_dataset
  class_names: [hand_wave, idle]
  quantization_path: /Users/maksym.solovianchyk/Documents/Graduation_Internship/radar_ai_detector/Recorded_data/tf_dataset

preprocessing:
   rescaling:
      scale: 1/255
      offset: 0
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: grayscale

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: int8
   export_dir: quantized_models

mlflow:
   uri: ./tf/src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./tf/src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
